#!/bin/bash
# ═══════════════════════════════════════════════════════════
# Medallion Daily Refresh — 5:00 AM
# Reads Medallion_Architecture_V3.md, audits live systems,
# updates the "Services Running" section with fresh status.
# ═══════════════════════════════════════════════════════════

set -e

VAULT="/home/krsna/friday-gateway/vault"
DOC="$VAULT/1_Projects/Medallion_Architecture_V3.md"
BACKUP="$VAULT/4_Archives/Medallion_Architecture_V3_$(date +%Y%m%d).md"
LOG="$VAULT/3_Resources/system_health_log.md"

echo "[MEDALLION REFRESH] Starting daily audit at $(date -Iseconds)"

# ── 1. Snapshot current doc to Archives ──────────────────
cp "$DOC" "$BACKUP"
echo "[MEDALLION] Backed up to $(basename $BACKUP)"

# ── 2. Audit Live Systems ────────────────────────────────
audit_mosquitto() {
  if systemctl --user is-active --quiet mosquitto 2>/dev/null; then
    ss -tlnp | grep -q ":1883" && echo "✅ mosquitto" || echo "⚠️  mosquitto (port not listening)"
  else
    echo "❌  mosquitto (stopped)"
  fi
}

audit_surrealdb() {
  if ss -tlnp | grep -q ":8000"; then
    echo "✅ surrealdb-bronze (:8000)"
  else
    echo "❌  surrealdb-bronze (not listening)"
  fi
}

audit_vanguard() {
  if curl -sf http://localhost:3009/health > /dev/null 2>&1; then
    UPTIME=$(curl -sf http://localhost:3009/health 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(f\"{d.get('uptime',0):.0f}s\")" 2>/dev/null || echo "unknown")
    echo "✅ vanguard-paperclip (:3009, uptime ${UPTIME})"
  else
    echo "❌  vanguard-paperclip (unreachable)"
  fi
}

audit_paperclip_ui() {
  if curl -sf http://localhost:3100/ > /dev/null 2>&1; then
    echo "✅ paperclip-ui (:3100)"
  else
    echo "❌  paperclip-ui (unreachable)"
  fi
}

audit_mqtt_bridge() {
  if pgrep -f "mqtt_to_surreal\|mqtt-bridge" > /dev/null 2>&1; then
    echo "✅ mqtt-to-surrealdb bridge"
  else
    echo "⚠️  mqtt-to-surrealdb bridge (not running)"
  fi
}

audit_vault_sync() {
  LOCAL=$(find "$VAULT" -type f | wc -l)
  REMOTE=$(rclone ls vault-crypt: 2>/dev/null | wc -l)
  if [ "$LOCAL" = "$REMOTE" ]; then
    echo "✅ vault sync (${LOCAL} files — in sync)"
  else
    echo "⚠️  vault sync (local:${LOCAL} remote:${REMOTE} — out of sync)"
  fi
}

audit_github() {
  if curl -sf -o /dev/null -w "%{http_code}" \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    https://api.github.com/repos/cloudjoe-lab/friday-gateway 2>/dev/null | grep -q "200"; then
    echo "✅ github.com/cloudjoe-lab/friday-gateway"
  else
    echo "⚠️  GitHub repo (unreachable)"
  fi
}

# ── 3. Build audit report ────────────────────────────────
UPDATED=$(date -Iseconds | sed 's/+00:00/UTC/')
AUDIT_BLOCK="### What's Live Now — $UPDATED

| Service | Status |
|---------|--------|
| $(audit_mosquitto) | MQTT Broker (:1883) |
| $(audit_surrealdb) | SurrealDB Bronze Layer (:8000) |
| $(audit_vanguard) | Vanguard Paperclip API (:3009) |
| $(audit_paperclip_ui) | Paperclip AI Dashboard (:3100) |
| $(audit_mqtt_bridge) | MQTT → SurrealDB Bridge |
| $(audit_vault_sync) | Encrypted vault → Google Drive |
| $(audit_github) | GitHub Repository |

> Auto-generated by Vanguard Cron — Medallion Daily Refresh"

# ── 4. Update the document ──────────────────────────────
# Replace the "What's Live Now" section
python3 << 'PYEOF'
import re, sys
from datetime import datetime

doc_path = "/home/krsna/friday-gateway/vault/1_Projects/Medallion_Architecture_V3.md"
with open(doc_path, "r") as f:
    content = f.read()

# Generate fresh audit block
import subprocess, json

def run(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True).stdout.strip()

services = []

# Mosquitto
r = run("systemctl --user is-active --quiet mosquitto 2>/dev/null && ss -tlnp | grep -q ':1883' && echo 'up' || echo 'warn'")
services.append(("MQTT Broker", "✅" if "up" in r else "⚠️"))

# SurrealDB
r = run("ss -tlnp | grep -q ':8000' && echo 'up' || echo 'down'")
services.append(("SurrealDB Bronze", "✅" if "up" in r else "❌"))

# Vanguard
r = run("curl -sf http://localhost:3009/health 2>/dev/null | python3 -c \"import json,sys; d=json.load(sys.stdin); print(d.get('status','?'))\" 2>/dev/null || echo 'down'")
services.append(("Vanguard Paperclip", "✅ operational" if "ok" in r else f"❌ {r}"))

# Paperclip UI
r = run("curl -sf http://localhost:3100/ 2>/dev/null | head -1 | grep -q 'html' && echo 'up' || echo 'down'")
services.append(("Paperclip UI", "✅" if "up" in r else "❌"))

# MQTT Bridge
r = run("pgrep -f 'mqtt_to_surreal|mqtt-bridge' > /dev/null 2>&1 && echo 'up' || echo 'down'")
services.append(("MQTT→SurrealDB Bridge", "✅" if "up" in r else "⚠️"))

# Vault sync
local = run("find /home/krsna/friday-gateway/vault -type f | wc -l")
remote = run("rclone ls vault-crypt: 2>/dev/null | wc -l")
sync_status = "✅" if local == remote else "⚠️"
services.append(("Vault Sync", f"{sync_status} ({local} files)"))

# GitHub
r = run("curl -sf -o /dev/null -w '%{http_code}' -H 'Authorization: Bearer ' + os.environ.get('GITHUB_TOKEN','') + ' https://api.github.com/repos/cloudjoe-lab/friday-gateway 2>/dev/null")
services.append(("GitHub Repo", "✅" if "200" in r else "⚠️"))

# PM2 Vanguard
r = run("pm2 jlist 2>/dev/null | python3 -c \"import json,sys; apps=json.load(sys.stdin); print(any(a.get('pm2_env',{}).get('status')=='online' for a in apps))\" 2>/dev/null || echo 'False'")
services.append(("PM2 Vanguard", "✅" if "True" in r else "⚠️"))

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

table_rows = "\n".join([f"| {name} | {status} |" for name, status in services])
audit_block = f"""### What's Live Now — {timestamp}

| Service | Status |
|---------|--------|
{table_rows}

> Auto-generated by Vanguard Cron — Medallion Daily Refresh
> Previous archived at `4_Archives/Medallion_Architecture_V3_*.md`
"""

# Find and replace the "What's Live Now" section (only first occurrence)
pattern = r"### What's Live Now — [^\n]+\n\n\| Service \| Status \|\n\|---------|--------\|\n.*?(?=\n---|\n##|\Z)"
content = re.sub(pattern, audit_block.rstrip() + "\n", content, count=1, flags=re.DOTALL)

# Update document version in footer
content = re.sub(
    r"\*Document Version: \d+\.\d+",
    f"*Document Version: 3.1",
    content
)
content = re.sub(
    r"\*Authored By:.*",
    f"*Authored By: Friday (Synthesized from CJ's corrections)*\n*Last Refresh: {timestamp}*",
    content
)

with open(doc_path, "w") as f:
    f.write(content)

print(f"[MEDALLION] Document updated successfully")
print(f"[MEDALLION] Services checked: {len(services)}")
PYEOF

echo "[MEDALLION] Refresh complete — $(basename $DOC) updated"
echo "[MEDALLION] Archive copy: $(basename $BACKUP)"
